### ISSUE TITLE
error processing webhook events

### ISSUE THREAD

**Issue by jerrywcy** [trashhalo/obsidian-webhooks#13]
Some time ago I posted some requests(I have forgotten what requests I have made) but now no matter what file I am trying to write to, I told me like 
![image](https://user-images.githubusercontent.com/34678939/148629255-8bcbb552-f1f3-4e2c-bbce-b81edf4d25a2.png)
and I tried clean buffer but it didn't work...
not sure what had happened and what should I do

**Comment by jerrywcy** [comment]
I have deleted the folder but the next time I tried `curl -X POST -d "test" "****?path=test/test.md"` the folder RSS/ was recreacted and the same error message popped up

**Comment by TheAntiSnipe** [comment]
This is interesting, I had the exact same issue, I was fiddling with the webhook URL entry when it happened. I'm wondering if you managed to solve it? I'm thinking of poking around the code now.

**Comment by zhaokoh** [comment]
(Similar problem in #18, cross-posting) Same issue for me. Tried creating a brand new vault, reinstalling the plugin, clearing the buffer on the website, etc. None work. Same error. The problem persisted even when I make a POST request with a different folder.

**Comment by trashhalo** [comment]
Would you be open to jumping on a zoom with me tomorrow for 10 minutes to debug this?

**Comment by zhaokoh** [comment]
Sure, I am currently in the AEST timezone, so we may need to tee up a time suitable for both of us (I assume you are in the US)?

**Comment by zhaokoh** [comment]
@trashhalo Part of me wonders if the error was stuck in a "queue-like" mechanism (I am thinking MQTT) and has an error recovery that keeps sending past messages and not cleared from the queue (which is why the clear buffer was developed I am guessing). But in this case, it seems the "message" is still in the queue somehow (or cached?).

**Comment by zhaokoh** [comment]
(Cross-posting, same as issue #18) Cleared the buffer again this morning and everything seems working now. Thanks @trashhalo
