### ISSUE TITLE
Response to preflight request doesn't pass access control check

### ISSUE THREAD

**Issue by bwydoogh** [trashhalo/obsidian-webhooks#17]
See those error messages in the console (I am on the latest version of Obsidian, 0.14.7)

Access to fetch at 'https://us-central1-obsidian-buffer.cloudfunctions.net/wipe' from origin 'app://obsidian.md' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.

Any clue?

**Comment by trashhalo** [comment]
Hey! Sorry about that, I had a billing error and it went into a junk folder in my email. Ive fixed the billing problem and ive updated my email settings to capture this if it happens again.

The result was google downgraded us to the free plan which disabled many of the project's key features.

Fixed!
