### ISSUE TITLE
Persistent Error

### ISSUE THREAD

**Issue by reidpat** [trashhalo/obsidian-webhooks#18]
Getting an error whenever I try to use the plugin:

"Error processing webhook events, Error: ENOENT: no such file or directory, mkdir 'C:\Obsidian Notes\REDACTED'

I did make a mistake in my request and put in a non existent folder. But now nothing will run and no matter what URL I post to it will only come back with this error.

Tried clearing buffer, uninstalling plugin, clearing cache, restarting obsidian, restarting computer. Nothing worked

**Comment by lehan-musthafa** [comment]
This is happening for me too. Any updates on this?

**Comment by zhaokoh** [comment]
Same issue for me. Tried creating a brand new vault, reinstalling the plugin, clearing the buffer on the website, etc. None work. Same error. The problem persisted even when I make a POST request with a different folder.

**Comment by trashhalo** [comment]
Im struggling to reproduce this. Would you be able to show me whats in your developer tools console?

On Mac its: View menu, Toggle Developer Tools? Im looking for lines that look like this

<img width="527" alt="Screenshot 2023-02-24 at 1 01 40 PM" src="https://user-images.githubusercontent.com/177491/221255236-a55f0643-171f-4521-8d7b-8ae63864dbd5.png">

**Comment by lehan-musthafa** [comment]
I sent a request from postman to the following URL: https://us-central1-obsidian-buffer.cloudfunctions.net/webhook/.....?path=Captures/Emails.md
But it throws an error. Here is the screenshot of the developer console:

<img width="533" alt="console" src="https://user-images.githubusercontent.com/73033947/221278955-6c3fc1df-a553-4af1-928b-f0c63b186f44.png">

**Comment by lehan-musthafa** [comment]
Also mentioning the fact that this error started occurring after I set up an automated webhook event (I don't remember well, but it was on either IFTTT or Make).

**Comment by trashhalo** [comment]
You know every person Ive seen this happen to has had a windows account! Im developing this on a mac, I wonder if thats part of the puzzle

**Comment by trashhalo** [comment]
Okay Ive had some time to work on this.
1. The **clear buffer** button was not doing what it needed to do to put accounts into healthy states. so if you had a message you couldnt process you would never be able to to get out of the bad state. **So please try and press the clear buffer button once again.**
2. Ive added a bunch more logging on the server to look for issues. Let me know if you hit something and I will have more data to debug this now.

**Comment by zhaokoh** [comment]
Sorry for this late reply, Mac user here :) and I am using Shortcuts to submit the POST request and here is the error in the developer console:
![image](https://user-images.githubusercontent.com/10231698/221314073-77dbce83-1ea2-4f1f-93fb-95cdf3f3db5e.png)

**Comment by zhaokoh** [comment]
Woohoo!!! Clear the buffer again this morning, and the error is gone and it works now!!! Thanks @trashhalo. Much appreciated. Very happy.

**Comment by lehan-musthafa** [comment]
For me too!!! Happy start for the day
