### ISSUE TITLE
Install issue

### ISSUE THREAD

**Issue by TfTHacker** [trashhalo/obsidian-webhooks#3]
Hi there,
Your plugin won't install. The reason is that in the community plugin list you registered your plugin id with : `obsidian-webhooks` and in your manifest.json on your repository it is `obsidian-webhooks-plugin`.

I would recommend changing the id in your manifest.json (easier than a request to the community list)

**Comment by trashhalo** [comment]
UH OH THANK YOU!

**Comment by trashhalo** [comment]
Can you try now?

**Comment by TfTHacker** [comment]
So I now see a second problem. The manifest.json file in your release seems corrupt.  You may need to reupload that file.

**Comment by trashhalo** [comment]
Re-uploaded. Let me know if you hit other issues

**Comment by TfTHacker** [comment]
working now!
