### ISSUE TITLE
IFTTT Repeatedly sends webhook updates after one trigger

### ISSUE THREAD

**Issue by Aaron-Bopp** [trashhalo/obsidian-webhooks#4]
I set up a IFTTT for a Google assistant trigger that then hits the webhook, and it does insert the text to my vault, but it does so repeatedly after one trigger. Disconnecting and archiving the IFTTT trigger, or closing obsidian doesn't stop it, but logging out of the plugin does. I think it might be related to me being on a university network, so I will update when I get home.

**Comment by Aaron-Bopp** [comment]
Yeah, it still doesn't work at home. I tried it with the spotify trigger as well and same issue. I have it setup exactly as you described in the github.

**Comment by trashhalo** [comment]
User on discord reported the same thing. Going to try to fix today

**Comment by trashhalo** [comment]
@Aaron-Bopp version 0.0.3 has fix! thanks for reporting
