### ISSUE TITLE
TypeError

### ISSUE THREAD

**Issue by link-ding** [trashhalo/obsidian-webhooks#8]
I want an automation when I starred article in the inoreader and add the content to obsidian, but I got the error.
![image](https://user-images.githubusercontent.com/49264539/142744466-af87de2f-87d3-4927-b70e-e64f2ec67d17.png)

This is the setting of IFTTT.
![image](https://user-images.githubusercontent.com/49264539/142744469-d486fe44-8088-498d-b553-4523cca6a679.png)

**Comment by trashhalo** [comment]
@link-ding It would be helpful if I knew the email you used to sign up for service. If you don't want to add a comment with it can you email me: stephen [`at] solka.dev I can use that to look at your data to better understand what's going wrong here.

**Comment by link-ding** [comment]
> @link-ding It would be helpful if I knew the email you used to sign up for service. If you don't want to add a comment with it can you email me: stephen [`at] solka.dev I can use that to look at your data to better understand what's going wrong here.

sent

**Comment by trashhalo** [comment]
Fixed! You should be good to go now. One thing I noticed with this ifttt/inoreader setup you have it dumps the content as html into the note. Obsidian handles this fine in preview mode but its kind of ugly in the editor.

Would it be helpful to have an option to convert html to markdown?

<img width="872" alt="Screen Shot 2021-11-22 at 7 55 10 AM" src="https://user-images.githubusercontent.com/177491/142865582-f013c1e0-92ef-483d-8b82-963c731587b0.png">
<img width="862" alt="Screen Shot 2021-11-22 at 7 54 26 AM" src="https://user-images.githubusercontent.com/177491/142865584-89f95853-c7f9-45e3-89f9-89f77d716d0a.png">

**Comment by link-ding** [comment]
Thanks for fixing this, It works now. It must be helpful we can get markdown in obsidian. 
Aother question, is there any way I can create a new markdown file with the article title?

**Comment by trashhalo** [comment]
<img width="665" alt="Screen Shot 2021-11-22 at 1 27 04 PM" src="https://user-images.githubusercontent.com/177491/142915681-56e52fe4-b087-4515-bc22-487172353d9c.png">

Like this! Tested and it seems to do the right thing. I don't know what would happen if the title had funny characters in its name. `/[]()!:`

**Comment by trashhalo** [comment]
I'll let you know when I update the plugin to make html turn into markdown.

**Comment by link-ding** [comment]
> I'll let you know when I update the plugin to make html turn into markdown.

Thanks, that will be great if there have a markdown format

**Comment by trashhalo** [comment]
@link-ding issue to follow for updates. https://github.com/trashhalo/obsidian-webhooks/issues/10
