### ISSUE TITLE
Conditions for appending

### ISSUE THREAD

**Issue by cjl12377** [trashhalo/obsidian-webhooks#9]
Thanks for making this app! I was wondering if its possible to allow conditions to add a line or space to any input to a note?

**Comment by trashhalo** [comment]
@cjl12377 Im not sure I understand. Maybe you can say more about what you'd like?

**Comment by jamie9090** [comment]
I think I can comment here as I'm experiencing a similar issue.

I'm basically appending a note with a line. However, my current integration tool can't detect a line break before/after.

So I'm using the <br> command to manually add line breaks when appending, but it has its own formatting issues, especially when using Obsidian as bit more of a WYSIWIG editor.

So I think what CJ is requesting is a way to have a setting where we automatically add a line break when appending.

I would like to put my hand up for that one too!

**Comment by trashhalo** [comment]
Would you like a checkbox in the plugin to always append a new line. or would you like a option on the webhook url to append a new line if set. &newline=true.

**Comment by jamie9090** [comment]
I would love a checkbox if possible! But happy with whatever is easiest

**Comment by trashhalo** [comment]
@jamie9090 done. plugin version 0.0.5 has a new line setting. it defaults to no new line, but you can set it to linux/unix/mac style new lines or windows style new lines.

**Comment by jamie9090** [comment]
Amazing. Thank you
